image: node:16.14.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - yarn install --cache .npm --prefer-offline


build1:
  stage: build
  script:
  - yarn dev
  artifacts:
    expire_in: 1 week
    paths:
    - 'dist/'

test1:
  stage: test
  script:
  - "CI=true npm test" 
  dependencies:
  - build1

pages:
  stage: deploy
  script:
  - mv public _public
  - mv dist public
  only:
  - master
  artifacts:
    paths:
    - public
  dependencies:
  - build1