name: GitHub Actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build project
        run: yarn build
      - name: Clone master branch
        run: git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/culture.git" --branch master

      - name: Set git config and add changes
        run: |
            git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
            git config --global user.name "${GITHUB_ACTOR}"
            git add --all
        working-directory: ./dist

      - name: Push and send notification
        run: |
            COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
            git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
            # Only if repo have changes
            git commit -m "${COMMIT_MESSAGE}"
            git push origin master
        working-directory: ./dist
